### ISSUE TITLE
help me..(

### ISSUE THREAD

**Issue by kxr3nn** [ShimmyMySherbet/SherbetVaults#1]
Hello, how i can fix this?
I have installed all the libraries attached in the 'Libraries' folder
And still in the console I see this:

[loading] SherbetVaults
[Error] Could not find dependency: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[Error] Could not find dependency: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

**Comment by ShimmyMySherbet** [comment]
You need to add the netstandard library to your libraries folder. While it is a standard library, I'll likely include it with future releases.
[netstandard.zip](https://github.com/ShimmyMySherbet/SherbetVaults/files/8703926/netstandard.zip)

**Comment by TeemoCell** [comment]
You can find a list of libraries here. 
https://unturned.uedit.co/RocketMod/PluginLibraries/
