### ISSUE TITLE
Vaults stop working after some time

### ISSUE THREAD

**Issue by setpopa** [ShimmyMySherbet/SherbetVaults#11]
Plugin works fine ,but suddenly after some time it stop work and i need restart server(or reload), same happen when Im using VaultPlugin2.

**Comment by ShimmyMySherbet** [comment]
If the same issue is also happening with VaultPlugin2, it *could* be an incompatible plugin. Though it is unlikely.

This is most likely an issue relating to your database closing connections unexpectedly.

The latest version of SherbetVaults now forces transient connections. While this might slightly reduce performance the first few times the vault command is run, it should also make it a lot more reliable.

You can download the latest version of the plugin here: https://github.com/ShimmyMySherbet/SherbetVaults/releases

If you are still having issues after updating, feel free to re-open the issue.
