### ISSUE TITLE
You dont have access to any vaults

### ISSUE THREAD

**Issue by LeandroTheDev** [ShimmyMySherbet/SherbetVaults#14]
Hello, i dont understand what i need to do to give access a vault to the default group.

![image](https://user-images.githubusercontent.com/106118473/210078915-64742758-daa2-4319-86b3-184fe3f735da.png)

with this configurations continues saying that i dont have acess.

**Comment by ShimmyMySherbet** [comment]
You need to add permissions for the `vault` command, and the permissions for the individual vaults, e.g., `Vault.default` in the rocket permissions config.
