### ISSUE TITLE
I'm not sure why its not loading the plugin

### ISSUE THREAD

**Issue by JakeyT31** [ShimmyMySherbet/SherbetVaults#15]
![Capture](https://user-images.githubusercontent.com/118773062/224463606-0b5a21b0-bcc1-4a88-971d-19de3c15fa52.PNG)

**Comment by papershredder432** [comment]
Your MySQL information is incorrect.

**Comment by ShimmyMySherbet** [comment]
I'm assuming you've fixed this issue at this point, so I'm gonna close this issue.
