### ISSUE TITLE
Translating text doesn't work

### ISSUE THREAD

**Issue by CatzMR** [ShimmyMySherbet/SherbetVaults#2]
After I tried to translate it into Chinese, the plugin did not show any errors when loading, but I found that the translation file did not work in the game...

**Comment by ShimmyMySherbet** [comment]
As I mentioned in your issue <a href="https://github.com/ShimmyMySherbet/SherbetHome/issues/1">here</a>, you have most likely either broken the translations file, or set it up incorrectly.
Would you be able to send your translations file for me to check?

**Comment by ShimmyMySherbet** [comment]
This issue has been addressed in the latest <a href="https://github.com/ShimmyMySherbet/SherbetVaults/releases">pre-release</a>
Let me know if you're still having issues after updating, or have any other issues with the release.

**Comment by CatzMR** [comment]
It is recommended to separate the project restriction function and publish it as a separate plugin.

**Comment by CatzMR** [comment]
I hope to generate a new version, I can't find the required dependencies when using the compiler

**Comment by ShimmyMySherbet** [comment]
I temporarily removed the release since there was a bug preventing /vault and /vaults from working. I'll be re-releasing it soon.
Also, the restriction is for items in the vaults. It wouldn't make any sense to make it a separate plugin. It restricts what items a player can or cannot store in the vaults.

**Comment by CatzMR** [comment]
Hmm...

**Comment by ShimmyMySherbet** [comment]
Revision B for the 1.2 alpha has been released, you should see the plugin .zip download there now

**Comment by ShimmyMySherbet** [comment]
While as of now this issue is fixed. I'll leave it open until the next full version is released.

**Comment by ShimmyMySherbet** [comment]
This issue has now been fixed in the latest full release, https://github.com/ShimmyMySherbet/SherbetVaults/releases
