### ISSUE TITLE
Support for multiple servers on the same database

### ISSUE THREAD

**Issue by NVedsted** [ShimmyMySherbet/SherbetVaults#5]
It would be nice if it would become easier to have multiple servers with distinct vaults without having to create separate databases. I hope this is something you will consider. Since this will get opinionated quite fast, I will just keep this as an issue for now.

I see two ways to go about it:
 - Add the ability to change the table names through configuration. (Easily done with your current structure and probably a no-brainer to allow users to pick their own table name if they wish so.)
 - Introduce yet another key to the tables that distinguishes servers; either through configuration or some magic I am too new to Unturned to know, haha. This approach would also allow vaults to be shared across "server groups" by giving the servers the same identifier. With that being said, I am not sure if the plugin would properly handle the potential data races of having servers share the table in real-time.

Hoping to see something like this! Let me know if I can assist with anything. :)

**Comment by ShimmyMySherbet** [comment]
This is a good idea. And as you mentioned, the easiest way would be to allow the table name to be configured.
I already plan on changing the config a bit to reduce confusion around vault permissions. So I'll add this in as well.

**Comment by ShimmyMySherbet** [comment]
If anyone else wants to weigh in on this, feel free to.

**Comment by ShimmyMySherbet** [comment]
An option to rename the database tables has now been released in the latest release.

This should allow you to set up your database to store vaults for multiple servers without syncing them.

https://github.com/ShimmyMySherbet/SherbetVaults/releases
