### ISSUE TITLE
MySql.Data version mismatch

### ISSUE THREAD

**Issue by TheMarf80** [ShimmyMySherbet/SherbetVaults#8]
Hello Shimmy,

First of all great work i love your repos!!!!

But i have a smal problem and this is not with your vault it works very good. But i will try to explain.
I run 3 unturned server with Uconomy systems the plug-ins are Uconomy, Zaupshop and Zaupuconomyextentions.
This Plug-ins run on MySql.Data 8.0.18 and some other old DLL files.
You Vault Plug-in runs on MySql.Data 8.0.29 and the new other DLL files

When i install you Vault plug-in >> Uconomy + depend... crash.
When i recover Uconomy + depend... >> Your vault crash

The problem is the MySql.Data version mismatch.

So a long story short is there a way to seperate your dll file to for example /libraries/shimmy/*dll_files* (inside rocket folders)
What files do i need to edit on your project before i make a pack... from sln?

**Comment by ShimmyMySherbet** [comment]
You can try renaming the vault plugin's dependencies to use multiple versions of it, though there isn't much I can do to help.
If you wanted to compile this plugin with a different version of MySQL.Data, that would also be an option. Though, you would want to use the NuGet package manager in Visual Studio to do so.

**Comment by TheMarf80** [comment]
**Problem fixed**

Hello, Thanks for the feedback unfortunately there was one of your dependent NuGet dll's that needed the version 8.0.29.
But is have fount a workaround!
I just uploaded the the vault.dll and the new lib files with a new name, all the old lib file I left them on the old versions.
Now everything loads on start as it must be.

Just found one problem for you to fix this problem is in the original as in my workaround, When you execute the command for the 1e time after login it gives a error on execute. After that the commands works fine.

**Comment by ShimmyMySherbet** [comment]
In the future, if you have library issues, you can rename the library dll to have multiple versions of the same library.

Though the RocketExtensions and 0Harmony libraries you might want to avoid having multiple versions of if possible.
